yarnPath: .yarn/releases/yarn-2.1.1.js

pnpMode: loose
preferInteractive: true
defaultSemverRangePrefix: ""

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.js
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.js
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.js
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.js
    spec: "@yarnpkg/plugin-constraints"
